Resources:
  TUDublinEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-east-1a
      InstanceType: t2.micro
      KeyName: vockey
      ImageId: ami-0dfcb1ef8550277af
      SecurityGroups:
        - !Ref SecurityGroupSSH
      Tags:
        - Key: NameTest
          Value: Demo_Updated
  SecurityGroupSSH:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH in
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0